name: Build and Push

on:
  push:
    branches:
      - 'master'

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup yarn package
        run: cd web && yarn install --network-timeout 1000000
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: http://localhost:3000
          spec: cypress/integration/secret_spec.js
          start: yarn start
          working-directory: web
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Build and push
        id: docker_build
        uses: docker/build-push-action@v2
        with:
          build-args: |
            RECAPTCHA_KEY=${{ secrets.RECAPTCHA_KEY }}
          push: true
          tags: jhinze/vanishing-secrets:latest