name: Cypress Tests

on: [push, pull_request]

jobs:
  cypress-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: 16
      - name: Setup yarn package
        run: cd web && yarn install --network-timeout 1000000
      - name: Cypress run
        uses: cypress-io/github-action@v2
        with:
          wait-on: http://localhost:3000
          spec: cypress/integration/*
          start: yarn start
          working-directory: web
        env:
          REACT_APP_RECAPTCHA: '6LeIxAcTAAAAAJcZVRqyHh71UMIEGNQ_MXjiZKhI'
      - uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: web/cypress/screenshots
      - uses: actions/upload-artifact@v2
        if: always()
        with:
          name: cypress-videos
          path: web/cypress/videos